"""The two provider arms, behind one interface, each with a fake."""

from .composed import (
    ComposedArm,
    DormantSpeechRecognizer,
    FakeConversationModel,
    FakeSpeechRecognizer,
    LlmConversationModel,
    build_composed_arm,
)
from .interfaces import (
    ArmCapabilities,
    ArmDormant,
    AssistantAudio,
    AssistantTranscript,
    AssistantTurn,
    ConversationModel,
    LiveArm,
    LiveConversation,
    LiveEvent,
    PendingToolCall,
    ProviderError,
    RealtimeArm,
    SpeechRecognizer,
    SpeechStarted,
    SpeechStopped,
    ToolCallRequested,
    TurnDone,
    TurnRequest,
    UserTranscript,
)
from .openai_realtime import (
    DEFAULT_SERVER_VAD,
    OpenAiLiveConversation,
    OpenAiRealtimeArm,
    RealtimeProtocolError,
    RealtimeTransport,
    ScriptedRealtimeTransport,
    ServerVadEmulator,
    ServerVadRelay,
    WebsocketRealtimeTransport,
    build_openai_arm,
)
from .registry import build_all_arms, build_arm

__all__ = [
    "DEFAULT_SERVER_VAD",
    "ArmCapabilities",
    "ArmDormant",
    "AssistantAudio",
    "AssistantTranscript",
    "AssistantTurn",
    "ComposedArm",
    "ConversationModel",
    "DormantSpeechRecognizer",
    "FakeConversationModel",
    "FakeSpeechRecognizer",
    "LiveArm",
    "LiveConversation",
    "LiveEvent",
    "LlmConversationModel",
    "OpenAiLiveConversation",
    "OpenAiRealtimeArm",
    "PendingToolCall",
    "ProviderError",
    "RealtimeArm",
    "RealtimeProtocolError",
    "RealtimeTransport",
    "ScriptedRealtimeTransport",
    "ServerVadEmulator",
    "ServerVadRelay",
    "SpeechRecognizer",
    "SpeechStarted",
    "SpeechStopped",
    "ToolCallRequested",
    "TurnDone",
    "TurnRequest",
    "UserTranscript",
    "WebsocketRealtimeTransport",
    "build_all_arms",
    "build_arm",
    "build_composed_arm",
    "build_openai_arm",
]
