-- The other half of the claim query's WHERE clause, which has had no index since it was
-- written.
--
-- `jobs.claim` matches two disjoint sets of rows: a ready job that is due, and a `running`
-- job whose lease has expired (`STALE_LEASE_SECONDS`) — the reclaim that is the only thing
-- standing between a worker killed mid-job and a job nobody ever runs. Migration 0001's
-- `jobs_ready_idx` is partial on `state = 'ready'`, so it holds no `running` rows at all
-- and cannot answer the second arm. A `BitmapOr` needs an index path for *every* arm, so
-- with only one of them indexed the planner's remaining option was a sequential scan of
-- `jobs` — measured at 50,023 rows removed by filter and 618 shared buffers on a 50k-row
-- table, against 3 buffers with this index in place (motet#49).
--
-- That is the hottest query in the system: once per claim, and once more per queue per
-- drain pass to discover the queue is empty, so a long-lived `runner all --poll-seconds`
-- process runs it at least six times a sweep. And nothing prunes `jobs` — `complete()`
-- only flips the state to `done` — so the relation it was scanning grows for the life of
-- the deployment.
--
-- `(queue, locked_at)` rather than `(queue, run_at, id)`, which is the shape that would
-- have mirrored `jobs_ready_idx`: the reclaim arm filters on `locked_at`, and the mirrored
-- shape puts only `queue` in the index condition, so it reads every `running` row on the
-- queue and filters the lease in the heap. Neither shape avoids the `Sort` that
-- `ORDER BY run_at, id` needs — a `BitmapOr` produces no ordering, and Postgres will not
-- turn an `OR` into a `MergeAppend` — so ordering columns would be dead weight here.
--
-- Cheap to carry: the partial predicate means it holds only the jobs currently in flight,
-- which is bounded by the number of workers plus whatever they stranded, rather than by
-- every job ever run.
CREATE INDEX jobs_stale_idx ON jobs (queue, locked_at) WHERE state = 'running';
