-- The advisory-lock key a job's `serialize_key` maps onto, stored so the claim query can
-- read it without calling a function (motet#78).
--
-- Invariant 6 is enforced by taking a Postgres advisory lock on `lock_key(serialize_key)`
-- *after* the claim, and handing the row back with `defer()` when the key is already held.
-- That is correct and stays exactly as it is. What it is not is cheap at the head of a
-- burst: two thousand `integrate` rows for one busy user sit at the front of the queue
-- ordered by `run_at`, so every *other* worker claims-and-defers through all of them
-- before it reaches anybody else's work. Each cycle is milliseconds, so it is a busy-loop
-- tax rather than starvation — but it scales with the size of the burst, and it writes
-- `updated_at`, `run_at` and `attempts` on two thousand rows that nothing is doing.
--
-- With the key on the row, the claim's inner `SELECT` can skip a row whose key is held,
-- by reading `pg_locks` — a read with no side effects, which is the property that matters:
-- a function that *takes* the lock in the `WHERE` can fire for candidate rows that
-- `SKIP LOCKED` then discards, and the lease fence's soundness rests on "a deferred job
-- never starts a keeper", which is exactly what the current claim-then-lock order buys.
-- The lock-after-claim path therefore remains the correctness guarantee and the pre-filter
-- is an optimisation: a row whose key is taken between the filter and the lock still ends
-- in `defer()`, as it does today.
--
-- `bigint`, nullable, no index, no `CHECK`, and not generated. Nullable because a job
-- without a `serialize_key` has no key — and, deliberately, because a NULL here must read
-- as "not known to be held" rather than as "held": the claim spells that `lock_key IS NULL
-- OR NOT EXISTS (...)`, so a row this migration missed is still offered. The opposite
-- reading is the failure mode to fear, and it is silent — a queue whose rows are never
-- returned looks exactly like a queue with nothing in it.
--
-- No index because the column is never a search key: it is read off rows the two existing
-- partial indexes have already found, and compared against a handful of `pg_locks` rows.
-- An index would be write amplification on the queue table for nothing.
--
-- **No `CHECK ((serialize_key IS NULL) = (lock_key IS NULL))`, and that is a decision
-- rather than an omission.** It would make "a key with no lock_key" impossible, which
-- sounds strictly better — but the shape it has to survive is a rolling deploy, where an
-- old image whose `enqueue` does not know the column is inserting beside a new one. Under
-- the constraint every paste on the old image is a failed INSERT; without it those rows
-- simply fail open, are still offered, and are still serialized by `try_lock` — a
-- performance regression for the length of the deploy instead of an outage. Turning a
-- benign degradation into a hard failure is the wrong direction for a column whose whole
-- design is to fail open.
--
-- And **not `GENERATED ALWAYS AS (...) STORED`**, which would remove the second copy of
-- the hash entirely and is the first thing to reach for: Postgres refuses it, because
-- `convert_to` is `stable` rather than `immutable` and a generation expression must be
-- immutable. Recorded here so nobody derives that a second time.
ALTER TABLE jobs ADD COLUMN lock_key bigint;

-- Backfill the rows that are still in play. `done` and `failed` rows are never claimed
-- again, so the whole table does not need rewriting; `ready` and `running` is the set the
-- claim query can return.
--
-- The expression is `motet_workers.jobs.lock_key` transcribed into SQL: SHA-256 of the
-- key's UTF-8 bytes, first eight bytes, big-endian, **signed**. SHA-256 rather than
-- `hashtext` for the reason that function's docstring gives — `hashtext` is internal, has
-- no compatibility guarantee across major versions, and a hash that changed under a
-- database upgrade would silently stop serializing anything. `::bit(64)::bigint` is what
-- makes the top bit a sign bit rather than an overflow: `('x'||...)::bit(64)` is the
-- two's-complement bit pattern and the cast to `bigint` reads it as one, where an
-- arithmetic conversion would fail on any digest with the high bit set — half of them.
--
-- A transcription of a hash is exactly the kind of second copy that drifts, so
-- `workers/tests/test_pipeline.py::TestTheClaimSkipsBusyKeys::test_the_backfill_agrees_with_the_python_hash`
-- runs *this statement*, read out of this file, and pins what it writes against the Python
-- function over a set of keys including a non-ASCII one, the empty string, and one whose
-- digest has its top bit set. It runs once, here; every row written after this gets its key
-- from `jobs.enqueue`, which calls the Python function.
UPDATE jobs
SET lock_key = ('x' || encode(substring(sha256(convert_to(serialize_key, 'UTF8')) FROM 1 FOR 8), 'hex'))::bit(64)::bigint
WHERE serialize_key IS NOT NULL
  AND state IN ('ready', 'running');
