/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/feed.xml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rss Feed
         * @description The private, authenticated RSS feed Phase 1 ships instead of a player.
         *
         *     RSS buys background audio, offline, lockscreen, CarPlay, and speed control with zero
         *     iOS code. Audio is served from GCS behind signed URLs, so this document carries links,
         *     never bytes.
         */
        get: operations["rss_feed_feed_xml_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness, plus whether telemetry is actually wired.
         *
         *     The telemetry flags are not decoration. Exporters no-op silently when unconfigured, so
         *     without this an unmonitored process is indistinguishable from a quiet one.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/episodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Episode
         * @description Assemble a manual episode from unread news items, capped by duration.
         *
         *     Scripting, grounding validation, and TTS happen on the queue afterwards. Nothing is
         *     synthesized until grounding passes (invariant 3).
         */
        post: operations["create_episode_v1_episodes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/episodes/{episode_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Episode
         * @description An episode with its transcript — each claim beside the span it came from.
         */
        get: operations["get_episode_v1_episodes__episode_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/news-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List News Items
         * @description The backlog: deduped news items with their read state (invariant 5).
         */
        get: operations["list_news_items_v1_news_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources/paste": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Paste Source
         * @description Ingest pasted text as a source item.
         *
         *     Enqueues rather than processes: ingestion is serialized per user (invariant 6), so the
         *     work belongs to a worker draining the queue, never to the request thread.
         */
        post: operations["paste_source_v1_sources_paste_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ClaimModel
         * @description A reported assertion beside the span it came from (invariant 3).
         */
        ClaimModel: {
            span: components["schemas"]["SourceSpanModel"];
            /** Text */
            text: string;
        };
        /**
         * CreateEpisodeRequest
         * @description Phase 1 has manual episodes only: 'all unread', capped by duration.
         */
        CreateEpisodeRequest: {
            /** Max Duration Ms */
            max_duration_ms: number;
            /** Title */
            title: string;
        };
        /** EpisodeResponse */
        EpisodeResponse: {
            /** Duration Ms */
            duration_ms: number;
            /** Id */
            id: string;
            /** Segments */
            segments: components["schemas"]["SegmentResponse"][];
            /** Title */
            title: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Liveness plus enough telemetry wiring to tell 'quiet' from 'unmonitored'.
         */
        HealthResponse: {
            /**
             * Errors Configured
             * @description Whether error reporting is configured. False means errors go nowhere.
             */
            errors_configured: boolean;
            /**
             * Service
             * @description OTel service name this process reports as
             */
            service: string;
            /**
             * Status
             * @description 'ok' when the process is serving
             */
            status: string;
            /**
             * Telemetry Configured
             * @description Whether OTLP export is configured. False means telemetry is a no-op.
             */
            telemetry_configured: boolean;
        };
        /**
         * NewsItemResponse
         * @description A deduped story. Read state lives here, per invariant 5 — not per episode.
         */
        NewsItemResponse: {
            /** Id */
            id: string;
            /** Read */
            read: boolean;
            /** Source Item Ids */
            source_item_ids: string[];
            /** Summary */
            summary: string;
            /** Title */
            title: string;
        };
        /**
         * PasteRequest
         * @description A blob of text pasted in by hand — Phase 1's only ingestion route.
         */
        PasteRequest: {
            /** Text */
            text: string;
            /** Title */
            title: string;
        };
        /** SegmentResponse */
        SegmentResponse: {
            /** Claims */
            claims: components["schemas"]["ClaimModel"][];
            /** News Item Id */
            news_item_id: string;
        };
        /** SourceItemResponse */
        SourceItemResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
        };
        /**
         * SourceSpanModel
         * @description A half-open character range in a source item — what makes a claim checkable.
         */
        SourceSpanModel: {
            /** End */
            end: number;
            /** Source Item Id */
            source_item_id: string;
            /** Start */
            start: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    rss_feed_feed_xml_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The RSS feed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/rss+xml": unknown;
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    create_episode_v1_episodes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEpisodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_episode_v1_episodes__episode_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episode_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_news_items_v1_news_items_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsItemResponse"][];
                };
            };
        };
    };
    paste_source_v1_sources_paste_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
