"""Pick the mailbox and OAuth implementations for this process.

The same shape as ``motet_inference.registry``, and reading the **same variable**:
``MOTET_INFERENCE_MODE``, through ``motet_inference.mode.current_mode``. Gmail is a vendor,
and "may this process talk to a vendor" is one question with one answer.

That is deliberate rather than convenient. AGENTS.md records the specific failure a second
parser causes: two readings of the mode can disagree, and the disagreement is silent. A
``MOTET_SOURCES_MODE`` would reintroduce it in a worse form — a process could poll a real
mailbox and then dedup it with a fake model, or the reverse.

**PKCE lives here** rather than in either adapter, because the verifier is generated by the
API when it starts an authorization and checked by Google when the code is exchanged. It
belongs to the flow, not to a provider.
"""

from __future__ import annotations

import base64
import hashlib
import os
import secrets
from collections.abc import Mapping

from motet_inference.mode import current_mode

from .fakes import FakeMailClient, FakeOAuthClient
from .gmail import (
    DEFAULT_TIMEOUT_SECONDS,
    TIMEOUT_ENV,
    GmailMailClient,
    GmailOAuthClient,
    oauth_client_config,
)
from .interfaces import MailClient, OAuthClient


def build_oauth_client(env: Mapping[str, str] | None = None) -> OAuthClient:
    """The OAuth client for this process. Fake unless real mode is set explicitly.

    In fake mode the Google client id and secret are never read, which is what lets the
    whole connect-a-mailbox path run — and be tested — before the OAuth client exists.
    """
    environ = dict(os.environ) if env is None else dict(env)
    if current_mode(environ) != "real":
        return FakeOAuthClient()
    client_id, client_secret = oauth_client_config(environ)
    return GmailOAuthClient(
        client_id=client_id,
        client_secret=client_secret,
        timeout_seconds=_timeout(environ),
    )


def build_mail_client(access_token: str, env: Mapping[str, str] | None = None) -> MailClient:
    """The mailbox client, given an access token a worker has already unsealed.

    The token is a parameter rather than something resolved here: unsealing is the
    workers-only half of invariant 8, and a builder that could reach for a credential
    would be a builder the API could call.
    """
    environ = dict(os.environ) if env is None else dict(env)
    if current_mode(environ) != "real":
        return FakeMailClient()
    return GmailMailClient(access_token, timeout_seconds=_timeout(environ))


def new_pkce_pair() -> tuple[str, str]:
    """``(verifier, challenge)`` for one authorization, per RFC 7636.

    S256, never ``plain``. The verifier is stored server-side in ``oauth_states`` and the
    challenge travels in the URL, so an attacker who intercepts the redirect holds
    something they cannot reverse and therefore cannot redeem the code with.
    """
    verifier = secrets.token_urlsafe(64)
    digest = hashlib.sha256(verifier.encode("ascii")).digest()
    challenge = base64.urlsafe_b64encode(digest).decode("ascii").rstrip("=")
    return verifier, challenge


def new_oauth_state() -> str:
    """The CSRF token for one authorization.

    Sized as a secret because it is one: an attacker who can guess it can complete an
    authorization against somebody else's account.
    """
    return secrets.token_urlsafe(32)


def _timeout(environ: Mapping[str, str]) -> float:
    raw = environ.get(TIMEOUT_ENV, "").strip()
    if not raw:
        return DEFAULT_TIMEOUT_SECONDS
    try:
        seconds = float(raw)
    except ValueError:
        raise ValueError(f"{TIMEOUT_ENV}={raw!r} is not a number") from None
    if seconds <= 0:
        raise ValueError(f"{TIMEOUT_ENV}={raw!r} must be positive")
    return seconds
