"""Personal access tokens: the non-interactive way to prove you may call ``/v1``.

**Sign-off: Tadas, 2026-09-20.** He asked for "app passwords that bypass the human oauth
flow", was given the two shapes — a staging-only shared secret, or a real per-user token
system — and answered *"Go straight to PATs."* AGENTS.md, "A personal access token is a
third key to the same lock", is the record; this module is the store.

**Still one account.** Every row references ``users.motet-owner``, the row migration 0002
seeds, exactly as :mod:`motet_db.auth` does. A PAT is a second *key* to the one lock, not
an identity — which is why it carries the address of the session that minted it and is
re-checked against the sign-in allowlist on every request, like a session.

Three properties are the whole design, and each is a failure avoided rather than a
preference:

* **The plaintext exists once.** It is generated by the caller, returned in the response
  that mints it, and never stored, logged or returned again — only its SHA-256 is kept.
  This is :mod:`motet_db.auth`'s argument, and it applies harder here: a PAT is meant to
  be pasted into an agent's environment and lives for as long as the owner lets it, so a
  recoverable copy in the database would be a standing owner-equivalent credential sitting
  next to the data it protects.
* **Lookup is by hash, and comparison is constant-time.** The digest is the unique key, so
  finding a token is one full-length index probe, which gives a timing measurement nothing
  partial to work with — and what comes back is compared with :func:`hmac.compare_digest`
  anyway, so the property is local to this file rather than an argument about Postgres.
* **Revocation is a stamp.** ``revoked_at`` rather than a ``DELETE``, because with no
  database shell (invariant 10) this column is the only place "when did that token stop"
  can be asked.
"""

from __future__ import annotations

import hashlib
import hmac
import re
import secrets
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

import psycopg

from .ids import new_id
from .repo import _maybe_one, _one

#: The marker every Motet token starts with, and the reason the format has one at all.
#:
#: A leaked credential is only actionable if somebody can tell what it is. ``mot_`` makes a
#: token recognisable at a glance in a paste, a log, or a repository scan, and greppable in
#: an incident — which is the same reason GitHub's tokens say ``ghp_`` rather than being 40
#: anonymous characters.
TOKEN_MARKER: str = "mot_"

#: How many characters of the secret the stored ``prefix`` shows.
#:
#: Enough to tell two tokens apart in a list, and far too few to be worth anything: eight
#: base64url characters is 48 bits off a 256-bit secret, and an attacker holding the row
#: already holds the digest.
PREFIX_SECRET_CHARS: int = 8

#: What a token's environment label may be, after the API has slugified it. Checked here
#: too, because this function builds a string a client will match a prefix against and a
#: label carrying an underscore would make ``mot_<label>_`` ambiguous to read.
LABEL_RE: re.Pattern[str] = re.compile(r"\A[a-z0-9]{1,12}\Z")

#: The longest label the mint route accepts. Free text the owner writes, so it is bounded
#: rather than validated: this is a note to self, not an identifier.
MAX_LABEL_CHARS: int = 80


@dataclass(frozen=True)
class ApiToken:
    """One personal access token, as everything except the mint route ever sees it."""

    id: str
    user_id: str
    #: ``mot_<environment>_<first 8 of the secret>``. Display only.
    prefix: str
    #: The owner's own words for what this token is for.
    label: str
    #: The allowlisted address of the session that minted it.
    email: str
    created_at: datetime
    last_used_at: datetime | None
    expires_at: datetime | None
    revoked_at: datetime | None


@dataclass(frozen=True)
class MintedToken:
    """A token and the row recording it, for the one response that may carry the secret."""

    token: ApiToken
    #: The plaintext, which exists nowhere else and is never returned again. Out of the
    #: repr because an error reporter captures frame locals by their repr, and this object
    #: is a local of the route that mints it.
    secret: str = field(repr=False)


def token_digest(token: str) -> str:
    """The stored form of a token: hex SHA-256, and nothing reversible."""
    return hashlib.sha256(token.encode("utf-8")).hexdigest()


def new_token(label: str) -> str:
    """Mint a token string: ``mot_<label>_<32 random bytes, url-safe>``.

    Sized as a bearer secret rather than as an identifier, for
    :func:`motet_db.auth.new_session_token`'s reason — it is the only thing between the
    internet and an API that spends money. The label is an *environment* name, so a token
    says at a glance whether the thing it opens is staging or production.
    """
    if not LABEL_RE.match(label):
        raise ValueError(f"token label {label!r} must match {LABEL_RE.pattern}")
    return f"{TOKEN_MARKER}{label}_{secrets.token_urlsafe(32)}"


def looks_like_api_token(token: str) -> bool:
    """Whether a presented bearer is shaped like one of ours.

    The point is not validation — a token is verified by its digest or not at all. It is
    that a *session* token and a PAT arrive in the same header, and this is what decides
    which table a request probes. Without it every PAT would also cost a session lookup
    and every session a token lookup, on the path every request takes.

    **The parameter is called ``token`` deliberately, and so is every other local on this
    path.** ``sentry_sdk`` captures frame locals into an error report, and its default
    scrubber redacts a local whose *name* is on its denylist — which ``token`` and
    ``secret`` are, and which ``presented`` (the first draft's name) is not. So the naming
    is what keeps a bearer credential out of GlitchTip when something on the auth path
    raises; ``api/tests/test_api_tokens.py`` pins it rather than leaving it to be
    rediscovered.
    """
    return token.startswith(TOKEN_MARKER)


def create_token(
    conn: psycopg.Connection[Any],
    *,
    user_id: str,
    email: str,
    label: str,
    environment: str,
    ttl_seconds: int | None = None,
) -> MintedToken:
    """Mint a token, store its hash, and hand the plaintext back exactly once.

    **This function does not check the allowlist**, and no writer of this table may skip
    it — the same contract :func:`motet_db.auth.create_session_for_digest` states. The
    route that calls this has already required a signed-in session, which
    ``require_caller`` re-checks on every request, so the address is on the list by the
    time it gets here.
    """
    secret = new_token(environment)
    prefix = secret[: len(TOKEN_MARKER) + len(environment) + 1 + PREFIX_SECRET_CHARS]
    row = _one(
        conn,
        """
        INSERT INTO api_tokens (id, user_id, token_sha256, prefix, label, email, expires_at)
        VALUES (
            %s, %s, %s, %s, %s, %s,
            CASE WHEN %s::double precision IS NULL
                 THEN NULL
                 ELSE now() + make_interval(secs => %s) END
        )
        RETURNING id, user_id, prefix, label, email, created_at, last_used_at,
                  expires_at, revoked_at
        """,
        (
            new_id("pat"),
            user_id,
            token_digest(secret),
            prefix,
            label,
            email,
            ttl_seconds,
            ttl_seconds,
        ),
    )
    return MintedToken(token=_token(row), secret=secret)


#: How stale ``last_used_at`` may get before a request bothers to write it.
#:
#: The coarseness is the point, and it is :data:`motet_db.auth.TOUCH_INTERVAL_SECONDS`'
#: argument on the credential most likely to meet it: an agent driving the API makes
#: concurrent requests on one token, and an ``UPDATE`` per call takes an exclusive row
#: lock held until each request commits — so every call would wait out the one before it.
#: The column only ever answers "is anything still using this token".
TOUCH_INTERVAL_SECONDS: int = 5 * 60


def token_for_secret(conn: psycopg.Connection[Any], token: str) -> ApiToken | None:
    """Resolve a presented token to its row, touching ``last_used_at`` occasionally.

    Revoked and expired rows are filtered in the predicate rather than swept first, for
    :func:`motet_db.auth.session_for_token`'s reason: a token revoked a second ago must
    stop working now, and waiting for a cleanup job would make revocation advisory.

    The digest is compared again with :func:`hmac.compare_digest` after the probe. The
    index lookup is already a full-length equality on a hash, which leaks nothing partial
    — this makes "the comparison is constant-time" a property of this function rather than
    a claim about what Postgres does inside an index.
    """
    if not token:
        return None
    digest = token_digest(token)
    row = _maybe_one(
        conn,
        """
        SELECT id, user_id, token_sha256, prefix, label, email, created_at, last_used_at,
               expires_at, revoked_at
        FROM api_tokens
        WHERE token_sha256 = %s
          AND revoked_at IS NULL
          AND (expires_at IS NULL OR expires_at > now())
        """,
        (digest,),
    )
    if row is None or not hmac.compare_digest(str(row["token_sha256"]), digest):
        return None
    found = _token(row)
    conn.execute(
        """
        UPDATE api_tokens SET last_used_at = now()
        WHERE id = %s
          AND (last_used_at IS NULL OR last_used_at < now() - make_interval(secs => %s))
        """,
        (found.id, TOUCH_INTERVAL_SECONDS),
    )
    return found


#: The most tokens the list route returns. One account with a handful of agents, plus the
#: revoked rows kept for audit; a bound so the response cannot grow without one.
#:
#: There is no second page, which is why the ordering below puts live tokens first: this
#: list is the *only* surface that can revoke one (invariant 10, and ``logout-all``
#: deliberately does not touch tokens), so a live token falling off the end behind a
#: hundred revoked ones would be a credential nobody could reach. Paging is the answer if
#: an account ever holds more than this many live tokens at once, and nothing is close.
LIST_LIMIT: int = 100


def list_tokens(conn: psycopg.Connection[Any], user_id: str) -> list[ApiToken]:
    """Every token for a user: **live ones first**, then revoked, each newest first.

    Revoked rows stay in the list rather than disappearing, because "that token was live
    until Tuesday" is the question an audit asks and there is no other surface to ask it
    on (invariant 10). They sort *after* the live ones for :data:`LIST_LIMIT`'s reason —
    the list is the only way to revoke, so nothing that can still authenticate may be the
    thing the bound drops. No row here carries a secret; the API never sends one.
    """
    rows = conn.execute(
        """
        SELECT id, user_id, prefix, label, email, created_at, last_used_at,
               expires_at, revoked_at
        FROM api_tokens
        WHERE user_id = %s
        ORDER BY (revoked_at IS NULL) DESC, created_at DESC, id DESC
        LIMIT %s
        """,
        (user_id, LIST_LIMIT),
    ).fetchall()
    return [_token(row) for row in rows]


def revoke_token(conn: psycopg.Connection[Any], *, user_id: str, token_id: str) -> ApiToken | None:
    """Revoke one token. ``None`` when the user has no such token.

    Scoped to ``user_id`` in the predicate rather than checked after the read, so that the
    query cannot be written to revoke somebody else's row even when this is no longer a
    one-account deployment. Already-revoked is not an error — it returns the row unchanged,
    so a client retrying a revoke gets the same answer twice.
    """
    return _token_or_none(
        _maybe_one(
            conn,
            """
            UPDATE api_tokens
            SET revoked_at = coalesce(revoked_at, now())
            WHERE id = %s AND user_id = %s
            RETURNING id, user_id, prefix, label, email, created_at, last_used_at,
                      expires_at, revoked_at
            """,
            (token_id, user_id),
        )
    )


def _token_or_none(row: dict[str, Any] | None) -> ApiToken | None:
    return None if row is None else _token(row)


def _token(row: dict[str, Any]) -> ApiToken:
    return ApiToken(
        id=row["id"],
        user_id=row["user_id"],
        prefix=row["prefix"],
        label=row["label"],
        email=row["email"],
        created_at=row["created_at"],
        last_used_at=row["last_used_at"],
        expires_at=row["expires_at"],
        revoked_at=row["revoked_at"],
    )
